import type { CustomerLocale } from "./customerLanguage";

// Presentation labels only: stored project location values remain unchanged.
const englishLocationLabels: Readonly<Record<string, string>> = {
  "منطقة الرياض": "Riyadh Region",
  "منطقة مكة المكرمة": "Makkah Region",
  "منطقة المدينة المنورة": "Madinah Region",
  "منطقة القصيم": "Qassim Region",
  "المنطقة الشرقية": "Eastern Province",
  "منطقة عسير": "Asir Region",
  "منطقة تبوك": "Tabuk Region",
  "منطقة حائل": "Hail Region",
  "منطقة الحدود الشمالية": "Northern Borders Region",
  "منطقة جازان": "Jazan Region",
  "منطقة نجران": "Najran Region",
  "منطقة الباحة": "Al Bahah Region",
  "منطقة الجوف": "Al Jawf Region",
  "الرياض": "Riyadh",
  "الخرج": "Al Kharj",
  "الدرعية": "Diriyah",
  "الدوادمي": "Ad Dawadimi",
  "المجمعة": "Al Majmaah",
  "شقراء": "Shaqra",
  "الزلفي": "Az Zulfi",
  "وادي الدواسر": "Wadi Ad Dawasir",
  "عفيف": "Afif",
  "مكة المكرمة": "Makkah",
  "جدة": "Jeddah",
  "الطائف": "Taif",
  "رابغ": "Rabigh",
  "القنفذة": "Al Qunfudhah",
  "الليث": "Al Lith",
  "خليص": "Khulais",
  "المدينة المنورة": "Madinah",
  "ينبع": "Yanbu",
  "العلا": "Al Ula",
  "بدر": "Badr",
  "مهد الذهب": "Mahd Adh Dhahab",
  "بريدة": "Buraydah",
  "عنيزة": "Unaizah",
  "الرس": "Ar Rass",
  "البكيرية": "Al Bukayriyah",
  "المذنب": "Al Mithnab",
  "الدمام": "Dammam",
  "الخبر": "Al Khobar",
  "الظهران": "Dhahran",
  "الأحساء": "Al Ahsa",
  "الجبيل": "Jubail",
  "القطيف": "Qatif",
  "حفر الباطن": "Hafr Al Batin",
  "رأس تنورة": "Ras Tanura",
  "أبها": "Abha",
  "خميس مشيط": "Khamis Mushait",
  "بيشة": "Bisha",
  "محايل عسير": "Muhayil Asir",
  "النماص": "An Namas",
  "تبوك": "Tabuk",
  "ضباء": "Duba",
  "الوجه": "Al Wajh",
  "أملج": "Umluj",
  "حقل": "Haql",
  "حائل": "Hail",
  "بقعاء": "Baqaa",
  "عرعر": "Arar",
  "رفحاء": "Rafha",
  "طريف": "Turaif",
  "جازان": "Jazan",
  "صبيا": "Sabya",
  "أبو عريش": "Abu Arish",
  "صامطة": "Samtah",
  "بيش": "Bish",
  "نجران": "Najran",
  "شرورة": "Sharurah",
  "الباحة": "Al Bahah",
  "بلجرشي": "Baljurashi",
  "المندق": "Al Mandaq",
  "المخواة": "Al Makhwah",
  "سكاكا": "Sakaka",
  "دومة الجندل": "Dumat Al Jandal",
  "القريات": "Al Qurayyat",
  "طبرجل": "Tabarjal"
};

export function customerLocationLabel(value: string, locale: CustomerLocale): string {
  return locale === "ar" ? value : englishLocationLabels[value] ?? "Location requires review";
}
